import { Account, Transaction, Beneficiary, QuickAction } from '../types';

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: 'acc_tabungan_utama',
    type: 'checking',
    name: 'Tabungan Utama',
    balance: 12580500,
    currency: 'IDR',
    accountNumber: '****4821',
    color: '#1B3D7A',
  },
  {
    id: 'acc_tabungan',
    type: 'savings',
    name: 'Tabungan',
    balance: 45230000,
    currency: 'IDR',
    accountNumber: '****9314',
    color: '#10B981',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_001',
    title: 'Gojek',
    subtitle: 'Transportasi',
    amount: 25000,
    type: 'debit',
    category: 'transport',
    date: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'car-outline',
  },
  {
    id: 'tx_002',
    title: 'Tokopedia',
    subtitle: 'Belanja Online',
    amount: 175000,
    type: 'debit',
    category: 'shopping',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'bag-outline',
  },
  {
    id: 'tx_003',
    title: 'Gaji Bulanan',
    subtitle: 'PT. Maju Bersama',
    amount: 8500000,
    type: 'credit',
    category: 'income',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'briefcase-outline',
  },
  {
    id: 'tx_004',
    title: 'Shopee',
    subtitle: 'Belanja Online',
    amount: 89000,
    type: 'debit',
    category: 'belanja',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'storefront-outline',
  },
  {
    id: 'tx_005',
    title: 'Transfer ke Budi',
    subtitle: 'Transfer Pribadi',
    amount: 500000,
    type: 'debit',
    category: 'transfer',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'send-outline',
  },
  {
    id: 'tx_006',
    title: 'PLN',
    subtitle: 'Tagihan Listrik',
    amount: 450000,
    type: 'debit',
    category: 'tagihan',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'flash-outline',
  },
  {
    id: 'tx_007',
    title: 'Indomaret',
    subtitle: 'Belanja Harian',
    amount: 67500,
    type: 'debit',
    category: 'food',
    date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan_utama',
    status: 'completed',
    icon: 'cart-outline',
  },
  {
    id: 'tx_008',
    title: 'Bunga Tabungan',
    subtitle: 'Tabungan',
    amount: 125000,
    type: 'credit',
    category: 'income',
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    accountId: 'acc_tabungan',
    status: 'completed',
    icon: 'trending-up-outline',
  },
];

export const MOCK_BENEFICIARIES: Beneficiary[] = [
  { id: 'ben_001', name: 'Budi Santoso', accountNumber: '****1234', bankName: 'Bank BCA', initials: 'BS', color: '#3B82F6' },
  { id: 'ben_002', name: 'Sari Dewi', accountNumber: '****5678', bankName: 'Bank Mandiri', initials: 'SD', color: '#10B981' },
  { id: 'ben_003', name: 'Andi Wijaya', accountNumber: '****9012', bankName: 'Bank BNI', initials: 'AW', color: '#EF4444' },
  { id: 'ben_004', name: 'Maya Sari', accountNumber: '****3456', bankName: 'Bank BRI', initials: 'MS', color: '#F59E0B' },
  { id: 'ben_005', name: 'Rizki Ramadan', accountNumber: '****7890', bankName: 'CIMB Niaga', initials: 'RR', color: '#8B5CF6' },
];

export const QUICK_ACTIONS: QuickAction[] = [
  { type: 'transfer', label: 'Transfer', icon: 'swap-horizontal-outline', gradient: ['#3B82F6', '#2563EB'] },
  { type: 'pay', label: 'Pembayaran', icon: 'receipt-outline', gradient: ['#10B981', '#059669'] },
  { type: 'topup', label: 'Isi Ulang', icon: 'wallet-outline', gradient: ['#F59E0B', '#F97316'] },
  { type: 'exchange', label: 'Tukar Valuta', icon: 'repeat-outline', gradient: ['#14B8A6', '#0891B2'] },
  { type: 'savings', label: 'Tabungan', icon: 'trending-up-outline', gradient: ['#8B5CF6', '#7C3AED'] },
  { type: 'cards', label: 'Kartu', icon: 'card-outline', gradient: ['#EC4899', '#DB2777'] },
  { type: 'investment', label: 'Investasi', icon: 'bar-chart-outline', gradient: ['#6366F1', '#4F46E5'] },
  { type: 'more', label: 'Lainnya', icon: 'grid-outline', gradient: ['#94A3B8', '#64748B'] },
];

export const SUGGESTED_PROMPTS = [
  'Berapa saldo saya sekarang?',
  'Transfer Rp 100.000 ke Budi',
  'Kurs USD ke IDR berapa?',
  'Tampilkan transaksi terbaru saya',
  'Konversi 500 SGD ke IDR',
  'Siapa saja penerima favorit saya?',
];

export const CURRENCY_PAIRS = [
  { from: 'USD', to: 'IDR', flag: '🇮🇩' },
  { from: 'EUR', to: 'IDR', flag: '🇪🇺' },
  { from: 'SGD', to: 'IDR', flag: '🇸🇬' },
  { from: 'JPY', to: 'IDR', flag: '🇯🇵' },
];
